# The size of the private vault. Must be a multiple of 9 (e.g., 9, 18, 27, 36, 45, 54).
private-vault-size: 54

# Home limits are based on permissions.
# The permission will be smptools.homes.<group>
home-limits:
  default: 1
  vip: 5
  admin: 10

features:
  accelerated-growth:
    enabled: true
    multiplier: 2.0 # Crops grow 2 times faster